Fix pyright error
CI was failing on this line with the error:
```
error: Argument of type "float | None" cannot be assigned to parameter
"number" of type "_SupportsRound2[_T@round]" in function "round"
```

As the definition of `hits.relevance` says it can be None, it was causing
issues for pyright. Interestingly, only in ci though

Co-authored-by: Kalyan Dutia <kalyan.dutia@gmail.com>